"""Add wallet balance and transactions

Revision ID: 4dddb1a3fe47
Revises: 002_add_metrics_tables
Create Date: 2026-07-15 11:04:50.143799

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4dddb1a3fe47'
down_revision: Union[str, None] = '002_add_metrics_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tech_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tech_id'], ['tech_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('uq_proposal_request_tech', 'proposals', type_='unique')
    op.drop_constraint('referral_sources_user_id_key', 'referral_sources', type_='unique')
    op.drop_index('ix_referral_sources_user_id', table_name='referral_sources')
    op.create_index(op.f('ix_referral_sources_user_id'), 'referral_sources', ['user_id'], unique=True)
    op.add_column('tech_profiles', sa.Column('wallet_balance', sa.Numeric(precision=10, scale=2), server_default='15.00', nullable=False))
    op.add_column('tech_profiles', sa.Column('is_vip', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index('ix_user_sessions_login_at', table_name='user_sessions')
    op.drop_constraint('users_user_id_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_user_id_key', 'users', ['user_id'])
    op.create_index('ix_user_sessions_login_at', 'user_sessions', ['login_at'], unique=False)
    op.drop_column('tech_profiles', 'is_vip')
    op.drop_column('tech_profiles', 'wallet_balance')
    op.drop_index(op.f('ix_referral_sources_user_id'), table_name='referral_sources')
    op.create_index('ix_referral_sources_user_id', 'referral_sources', ['user_id'], unique=False)
    op.create_unique_constraint('referral_sources_user_id_key', 'referral_sources', ['user_id'])
    op.create_unique_constraint('uq_proposal_request_tech', 'proposals', ['request_id', 'tech_id'])
    op.drop_table('wallet_transactions')
    # ### end Alembic commands ###
