"""Add user_logs table

Revision ID: 7758affc0a81
Revises: 001_initial
Create Date: 2026-06-24 01:08:15.599587

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7758affc0a81'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('evento', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_logs_user_id'), 'user_logs', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_user_logs_user_id'), table_name='user_logs')
    op.drop_table('user_logs')
    # ### end Alembic commands ###
